### PR TITLE
Revert to default package version 1.0.0 if no package.json found

### LINKED ISSUE #36: AssetsCompiler 0.11.2 won't run for release/4.56 and below on CircleCI
For older version of cplace, release/4.56 and below, the AssetCompiler 0.11.2 won't run and will terminate with the following message.
```[exec] Sry main Repository is not called 'main' LESS Compilation might fail, please rename your folder to 'main'⇢ Checking whether newer version is available... ✓
     [exec] 
     [exec] [NPM] Could not find package.json in repo /home/circleci/collaborationFactory/******/packaging/~/target/software...
     [exec] ✹ Debugging enabled...
     [exec] Available cpus/cores: 2, rss: 61.72MB, heapTotal: 36.33MB, heapUsed: 19.08MB, external: 0.71MB
     [exec] ✹ (AssetsCompiler) Ignoring repo dependencies since localOnly execution...
     [exec] ✗ Failed to start assets compiler: (PackageVersion) version has not yet been initialized
     [exec] Error: (PackageVersion) version has not yet been initialized```

Here are some reference builds
- one 4.56 Build mit cplace-asc 0.10.0: https://circleci.com/gh/collaborationFactory/cplace/38630
- one 4.56 Build mit cplace-asc 0.11.2: https://circleci.com/gh/collaborationFactory/cplace/39635

### PR DESCRIPTION
**Pull request by rose-m**
Fixes #36 

Before release 4.57 the `package.json` file has not been copied during the build process. To make it fully backwards compatible without adding a change to the build.xml in all versions prior this is the fix.

### CODE REVIEW

File: src/model/PackageVersion.ts [hunk 1]
```diff
@@ -18,23 +18,24 @@ export class PackageVersion {
         const packagePath = path.resolve(mainRepo, PackageVersion.PACKAGE_JSON);
         if (!fs.existsSync(packagePath)) {
             console.warn(cwarn`[NPM] Could not find package.json in repo ${mainRepo}...`);
-            return null;
```
Comment (stophi-dev) [inline src/model/PackageVersion.ts]: So now the `_version` cannot be `null` anymore. (See Line 8).

Comment (rose-m) [reply src/model/PackageVersion.ts]: Thanks, updated it! :)

File: src/model/NPMResolver.ts [hunk 2]
```diff
@@ -30,7 +30,7 @@ export class NPMResolver {
     }
 
     public async resolve(): Promise<void> {
-        if (!PackageVersion.getOrNull()) {
+        if (!PackageVersion.get()) {
```
Comment (stophi-dev) [inline src/model/NPMResolver.ts]: Wait ... this case cannot happen, right?
`get()` will throw an error or return a valid version.

Comment (rose-m) [reply src/model/NPMResolver.ts]: Thank you - removed the `if` 🙈
