### PR TITLE
Watch HTML files to TypeScript compilation

### LINKED ISSUE #21: Modification in imported HTML template does not trigger a recompilation
Precondition: An imported HTML template included into an angular directive like this:
```
import * as myTemplate from './myTemplate.html';

export function myDirective() : ng.IDirective {
  template: myTemplate,
   ...
}
```
Steps to reproduce:
1. Start cplace-asc with `-w` (watch) and wait until it is finished.
2. Modify myTemplate.html and save file.

Expected result: The modification should be detected and recompiled.
Actual result: Assets compiler does nothing. The modification will only have an effect after cplace-asc was restarted.

Using cplace-asc version 0.8.0.

### PR DESCRIPTION
**Pull request by rose-m**
After adding support for importing HTML templates in #16 those files were not watched and thus modifications did not trigger a recompilation.

closes #21

### CODE REVIEW

File: src/executor/Scheduler.ts [hunk 1]
```diff
@@ -18,6 +18,12 @@ interface ISchedulingResult {
 }
 
 export class Scheduler {
+    private static readonly WATCH_PATTERNS = {
+        'ts': 'ts|htm?(l)',
```
Comment (stophi-dev) [inline src/executor/Scheduler.ts]: It actually works like intended: for `ts`, `html` and `htm` files.
Just a question of understanding: what kind of pattern is that? Is the syntax specified somewhere?

Comment (rose-m) [reply src/executor/Scheduler.ts]: This is a glob pattern - see: https://github.com/isaacs/node-glob#glob-primer
